// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpvfsvnixpmywrdghusj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdmZzdm5peHBteXdyZGdodXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4Njk4MjEsImV4cCI6MjA3NDQ0NTgyMX0.RSVccihItaKKjGbKXtA8aZtzQoaWceZrf4l1hDzOfgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});